---
version: '3'

tasks:
  default:
    silent: true
    cmds:
      - task -l

  test:
    desc: Run tests
    cmds:
      - go test -v ./...

  cover:
    desc: Run coverage
    cmds:
      - go test -coverprofile=coverage.out ./...

  build:
    desc: Build the frizbee binary
    cmds:
      - go build -ldflags="-X github.com/stacklok/frizbee/internal/cli.CLIVersion=local-dev" -o ./bin/ ./...

  lint:
    desc: Run linter
    cmds:
      - golangci-lint run --timeout 5m0s --config .golangci.yml